### ISSUE TITLE
FFmpeg error, but why???

### ISSUE THREAD

**Issue by muwaaaah** [AIFSH/ComfyUI-Hallo#15]
**ERROR:audio_separator.separator.separator:FFmpeg is not installed. Please install FFmpeg to use this package.**
Traceback (most recent call last):
  File "C:\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 379, in <module>
    inference_process(command_line_args)
  File "C:\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 176, in inference_process
    with AudioProcessor(
  File "C:\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\hallo\datasets\audio_processor.py", line 61, in __init__
    self.audio_separator = Separator(
  File "C:\Python\lib\site-packages\audio_separator\separator\separator.py", line 155, in __init__
    self.setup_accelerated_inferencing_device()
  File "C:\Python\lib\site-packages\audio_separator\separator\separator.py", line 162, in setup_accelerated_inferencing_device
    self.check_ffmpeg_installed()
  File "C:\Python\lib\site-packages\audio_separator\separator\separator.py", line 188, in check_ffmpeg_installed
    ffmpeg_version_output = subprocess.check_output(["ffmpeg", "-version"], text=True)
  File "C:\Python\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 
Prompt executed in 5.32 seconds

1. I already install ffmpeg    (*pip install ffmpeg)
2. this is pip list (*pip list)
entrypoints                        0.4
fairscale                          0.4.13
**ffmpeg                             1.4**
ffmpy                              0.3.0
filelock                           3.14.0

why ffmpeg error occured?

**Comment by AIFSH** [comment]
readme，and make sure you can use ffmpeg in the command

**Comment by muwaaaah** [comment]
Thank you, 

pip install >>>> not okay.
wingetui install >>>> okay.

I don't know why. but wingetui and install package is working

**Comment by muwaaaah** [comment]
Thank you,

pip install >>>> not okay.
wingetui install >>>> okay.

wingetui then install package is working great
