### ISSUE TITLE
issue: must be real number, not NoneType

### ISSUE THREAD

**Issue by gaoxuxu110** [AIFSH/ComfyUI-Hallo#17]
```python
[MoviePy] >>>> Building video H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\output\hallo_1718892662396749500.mp4
[MoviePy] Writing audio in hallo_1718892662396749500TEMP_MPY_wvf_snd.mp3
[MoviePy] Done.
[MoviePy] Writing video H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\output\hallo_1718892662396749500.mp4
Traceback (most recent call last):
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 379, in <module>
    inference_process(command_line_args)
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 351, in inference_process
    tensor_to_video(tensor_result, output_file, driving_audio_path)
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\custom_nodes\ComfyUI-Hallo\Hallo\hallo\utils\util.py", line 318, in tensor_to_video
    new_video_clip.write_videofile(output_video_file, fps=fps)
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\moviepy\decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\moviepy\video\VideoClip.py", line 338, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 201, in ffmpeg_write_video
    writer = FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 86, in __init__
    '-r', '%.02f' % fps,
          ~~~~~~~~^~~~~
TypeError: must be real number, not NoneType
#697 [HalloNode]: 940.07s
#700 [PreViewVideo]: 0.00s
```
![Snipaste_2024-06-20_22-38-18](https://github.com/AIFSH/ComfyUI-Hallo/assets/52225349/8eb30e89-b4eb-4afc-84d2-ce07dd568fbe)

**Comment by AIFSH** [comment]
readme，make sure you install ffmpeg in right way
