### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Neo-Pz** [AIFSH/ComfyUI-Hallo#18]
Traceback (most recent call last):
  File "/Users/Desktop/code/vision/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 379, in <module>
    inference_process(command_line_args)
  File "/Users/Desktop/code/vision/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 166, in inference_process
    source_image_lip_mask = image_processor.preprocess(
  File "/Users/Desktop/code/vision/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/hallo/datasets/image_processor.py", line 124, in preprocess
    face = sorted(faces, key=lambda x: (x["bbox"][2] - x["bbox"][0]) * (x["bbox"][3] - x["bbox"][1]))[-1]
IndexError: list index out of range

**Comment by gaoxuxu110** [comment]
Your face in the picture was not detected, try taking a different picture

**Comment by gaoxuxu110** [comment]
> Traceback (most recent call last): File "/Users/Desktop/code/vision/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 379, in inference_process(command_line_args) File "/Users/Desktop/code/vision/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 166, in inference_process source_image_lip_mask = image_processor.preprocess( File "/Users/Desktop/code/vision/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/hallo/datasets/image_processor.py", line 124, in preprocess face = sorted(faces, key=lambda x: (x["bbox"][2] - x["bbox"][0]) * (x["bbox"][3] - x["bbox"][1]))[-1] IndexError: list index out of range

Your face in the picture was not detected, try taking a different picture
