### ISSUE TITLE
YAML error

### ISSUE THREAD

**Issue by Mikerhinos** [AIFSH/ComfyUI-Hallo#2]
I'm getting this error :

```python
Traceback (most recent call last):
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 372, in <module>
    inference_process(command_line_args)
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 128, in inference_process
    config = OmegaConf.load(args.config)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\omegaconf\omegaconf.py", line 190, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\omegaconf\_utils.py", line 151, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\yaml\constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:torch._utils._rebuild_tensor_v2'
  in "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Hallo\tmp.yaml", line 37, column 15
  ```

Running on Pinokio's ComfyUI, not sure what's happening, maybe a version conflict ?

**Comment by PolarRobin** [comment]
I have the same message on Linux

**Comment by mpoplawskiatpp** [comment]
From the repo creator: "LoadImagePath node not LoadImage" - test this out. It fixed this bug on my setup!

**Comment by PolarRobin** [comment]
I have the same message on Linux


> From the repo creator: "LoadImagePath node not LoadImage" - test this out. It fixed this bug on my setup!

Solved it for me too, thanks!

**Comment by mpoplawskiatpp** [comment]
The funniest part is around 5 people made the same mistake :) Glad it's solved and working! KUDOS to the @AIFSH for this GREAT NODE!

**Comment by Mikerhinos** [comment]
![image](https://github.com/AIFSH/ComfyUI-Hallo/assets/18692487/ca00e56b-c30d-4497-8267-c2ba14eccc3e)
Unfortunately I still have the error.
