### ISSUE TITLE
太邪了！明明传入的只有2个参数……

### ISSUE THREAD

**Issue by O-O1024** [AIFSH/ComfyUI-Hallo#40]
```
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 376, in <module>
    inference_process(command_line_args)
  File "/root/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 182, in inference_process
    audio_emb, audio_length = audio_processor.preprocess(driving_audio_path, clip_length)
TypeError: AudioProcessor.preprocess() takes 2 positional arguments but 3 were given
```

**Comment by neverbiasu** [comment]
怎么你也在哈哈哈
