### ISSUE TITLE
cannot do a non-empty take from an empty axes

### ISSUE THREAD

**Issue by emircanerkul** [AIFSH/ComfyUI-Hallo#47]
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
2024-10-30 08:35:46.1817566 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\emirc\ComfyUI\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
No faces detected in the image. Using the entire image as the face region.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1730266546.361012    2452 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1730266546.369997    4404 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730266546.381410   16100 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
#face is invalid: 0
Traceback (most recent call last):
  File "C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 375, in <module>
    inference_process(command_line_args)
  File "C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 162, in inference_process
    source_image_lip_mask = image_processor.preprocess(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\hallo\datasets\image_processor.py", line 138, in preprocess
    get_mask(source_image_path, cache_dir, face_region_ratio)
  File "C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\hallo\utils\util.py", line 439, in get_mask
    get_lip_mask(landmarks, height, width, os.path.join(
  File "C:\Users\emirc\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\hallo\utils\util.py", line 391, in get_lip_mask
    lip_landmarks = np.take(landmarks, lip_ids, 0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emirc\ComfyUI\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 192, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emirc\ComfyUI\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
IndexError: cannot do a non-empty take from an empty axes.
Prompt executed in 7.91 seconds
```

**Comment by emircanerkul** [comment]
Using windows powershell venv python3 amd directml
