### ISSUE TITLE
Traceback ConstructorError(None, None)

### ISSUE THREAD

**Issue by revolvedai** [AIFSH/ComfyUI-Hallo#6]
Running on Linux,
Set cuda device to: 0

Total VRAM 24241 MB, total RAM 25033 MB

pytorch version: 2.1.0+cu118

xformers version: 0.0.22.post4+cu118

Set vram state to: NORMAL_VRAM

Device: cuda:0 NVIDIA RTX A5000 : native

VAE dtype: torch.bfloat16

Using xformers cross attention

----

  [0.5922, 0.5647, 0.5333]]]])" --driving_audio "/opt/rd/apps/ComfyUI/input/audio.wav" --output /opt/rd/apps/ComfyUI/output/hallo_1718727686477756178.mp4 --pose_weight 1.0 --face_weight 1.0 --lip_weight 1.0 --face_expand_ratio 1.2

Traceback (most recent call last):

  File "/opt/rd/apps/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 372, in <module>

    inference_process(command_line_args)

  File "/opt/rd/apps/ComfyUI/custom_nodes/ComfyUI-Hallo/Hallo/scripts/inference.py", line 128, in inference_process

    config = OmegaConf.load(args.config)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 188, in load

    obj = yaml.load(f, Loader=get_yaml_loader())

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load

    return loader.get_single_data()

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data

    return self.construct_document(node)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 60, in construct_document

    for dummy in generator:

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 413, in construct_yaml_map

    value = self.construct_mapping(node)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/omegaconf/_utils.py", line 151, in construct_mapping

    return super().construct_mapping(node, deep=deep)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 218, in construct_mapping

    return super().construct_mapping(node, deep=deep)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 143, in construct_mapping

    value = self.construct_object(value_node, deep=deep)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object

    data = constructor(self, node)

  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/yaml/constructor.py", line 427, in construct_undefined

    raise ConstructorError(None, None,

yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:torch._utils._rebuild_tensor_v2'

  in "/opt/rd/apps/ComfyUI/custom_nodes/ComfyUI-Hallo/tmp.yaml", line 37, column 15

Prompt executed in 12.23 seconds

**Comment by AIFSH** [comment]
img or audio filename pure en not include Chinese，try agin

**Comment by revolvedai** [comment]
No chinese, I used a.png for image and audio.wav for audio. Same issue. Freezes at 50% progress. Then same Constructor Errors.

**Comment by gaoxuxu110** [comment]
I have the same issue:
  File "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\.ext\Lib\site-packages\yaml\constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:torch._utils._rebuild_tensor_v2'
  in "H:\Deepfacelab\stablediffusion\ComfyUI-aki-v1.1_test\custom_nodes\ComfyUI-Hallo\tmp.yaml", line 37, column 15
#504 [HalloNode]: 9.33s

**Comment by mpoplawskiatpp** [comment]
your errors are the same as in Issue #2 
Which make five of us having the same critical error :( 
Unfortunately I can't figure out what causes this.

**Comment by AIFSH** [comment]
LoadImagePath node not LoadImage

**Comment by revolvedai** [comment]
I have been using LoadImagePath and am still having the issue. I recreated the workflow exactly while testing.

**Comment by AIFSH** [comment]
> I have been using LoadImagePath and am still having the issue. I recreated the workflow exactly while testing.

rename your audio filename，no "(1)" such character in it

**Comment by zdaar** [comment]
@revolvedai Maybe like me you were also using the wrong LoadAudioPath node. The one from ComfyUI AudioScheduler doesnt work with this workflow

**Comment by revolvedai** [comment]
Okay I figured it out. I was using the correct nodes. It was that the resolution of my image was too big. When I switched to 512x it worked. Could we perhaps add better error handling for resolution related errors so that the end user can realize what needs to be done? Thank you for this awesome node!

**Comment by revolvedai** [comment]
Do you need to use the Load Image Path and Load Audio Path node? There are so many conflicts in ComfyUI with those nodes so if you send someone a workflow to load, it shows all the conflicting nodes as necessary. That means the user downloads all the conflicting nodes too! Maybe some work for resolving the nodes or otherwise (ugh) making HalloLoadImagePath and HalloLoadAudioPath or something.
