### ISSUE TITLE
Triton and Onnxruntime error, Please advice

### ISSUE THREAD

**Issue by zappazack** [AIFSH/ComfyUI-Hallo#9]
Windows 11
Total VRAM 12282 MB, total RAM 32655 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
Using xformers cross attention

Error msg: 
C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\python.exe C:\Users\Intersurf\Documents\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py --config "C:\Users\Intersurf\Documents\ComfyUI\custom_nodes\ComfyUI-Hallo\tmp.yaml" --source_image "C:\Users\Intersurf\Documents\ComfyUI\input\ComfyUI_00140_.png" --driving_audio "C:\Users\Intersurf\Documents\ComfyUI\input\answer4.wav" --output C:\Users\Intersurf\Documents\ComfyUI\output\hallo_1718843364917587900.mp4 --pose_weight 1.0 --face_weight 1.0 --lip_weight 1.0 --face_expand_ratio 1.2
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2024-06-20 02:29:30.3508717 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-06-20 02:29:30.4092526 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Intersurf\Documents\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 372, in <module>
    inference_process(command_line_args)
  File "C:\Users\Intersurf\Documents\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 156, in inference_process
    with ImageProcessor(img_size, face_analysis_model_path) as image_processor:
  File "C:\Users\Intersurf\Documents\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\hallo\datasets\image_processor.py", line 97, in __init__
    self.face_analysis = FaceAnalysis(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

Prompt executed in 6.12 seconds

**Comment by rethink-studios** [comment]
(( same ))

**Comment by zappazack** [comment]
Triton is not originary available for windows so this wont work unless the code and required dependencies will change. Compiling procedure maybe possible but very difficult. Closing issue.

**Comment by Falkonar** [comment]
> Triton is not originary available for windows so this wont work unless the code and required dependencies will change. Compiling procedure maybe possible but very difficult. Closing issue.

we have the problem with Onnxruntime. Triron does not matter

**Comment by zappazack** [comment]
The issue is indeed only the Onnxruntime @Falkonar thx for pointing that out, Triton isnt any issue. Steps to solve:

1. Ensure that u have only the following Onnxruntime folders in ur "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\Lib\site-packages" (or similar path): onnxruntime-1.18.1.dist-info and onnxruntime. Delete all other Onnxruntime folders. If comfyui-Hallo does still not work also delete the remaining Onnxruntime folders. The broken Onnxruntime pipeline is a bug caused by comfyui update and all my nodes. I have suffered this problem several times the past days and my rembg (remove background) node doesnt work anymore.

2. Install the custom node rembg-comfyui-node cd to this folder and pip install -r requirements.txt. This will definitely install a working Onnxruntime pipeline. My comfy-Hallo works! Great work @AIFSH
